### ISSUE TITLE
[Enhancement] Change 'Consumer' to something unique

### ISSUE THREAD

**Issue by Neuroquila-n8fall** [N-Razzouk/dart_mq#1]
Hey there, 
I'm trying to circumvent some limitations posed by Riverpod with this package and so far it seems I'm having huge success using both in conjunction. Great!

One thing, however, is a little bit annoying: The name of the Consumer mixin. It clashes with the one of Riverpod and in general I think calling something library specific with something generic is a bad idea (i mean the same applies for Riverpod...)
I know the solution for this is to simply "import as" but I think this can be avoided - first and foremost because it is another thing that has to be maintained throughout the code, probably. 

I suggest adding a prefix to these mixins/interfaces like for example "Mq" so it's "MqConsumer". Of course this would be a breaking change but at the current stage perfectly manageable.

**Comment by N-Razzouk** [comment]
Hi there @Neuroquila-n8fall,
Thanks for opening an issue.
After giving it some thought, a better name would be `ConsumerMixin`, since it's a mixin not an object.
This has been added in v1.1.0, and `Consumer` shall be removed completely in v2.0.0.
